### ISSUE TITLE
Please make this one change if nothing else: test on line 168 

### ISSUE THREAD

**Issue by saifshaikh48** [KarmanS103/CS4500-FinalProject#8]
If you don't have time to do everything requested, for the implementation teams' sake, change `t_true(tensize->get(4)->equals(nothing));` to `t_true(tensize->get(4)->hash() == nothing->hash());`
The former will never pass regardless of Array implementation:
         - The Object* `nothing` is never added to the Array* `tensize` so it will never be equal to something in the array.
         - Not even the placeholders (all of type Object*) will ->equals(nothing) since they would be at different memory location(s) upon construction.

**Comment by haibero** [comment]
This has been done.  Sorry for the delay, getting to the other changes as I can.
